// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 17/10/2024 14:56:15
const configMerger = require("/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/plugins/**/*.{js,ts,mjs}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/stores/**/*.{js,ts,mjs}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/locales/**/*.{js,ts,mjs}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/composables/**/*.{js,ts,mjs}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/utils/**/*.{js,ts,mjs}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/arnaudsween/Documents/GC-Tech/vuejs-travel-card-component/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})()
